### ISSUE TITLE
Laravel 5.2, call to undefined function bindshared()

### ISSUE THREAD

**Issue by kolefield** [Cyber-Duck/laravel-wp-api#5]
bindshared was renamed to singleton.

Line 34 of LaravelWpApiServiceProvider should be changed to `$this->app->singleton`

**Comment by threesquared** [comment]
This repo is not maintained anymore. However I have updated my fork to fix this issue on version 2.1.0 
https://github.com/threesquared/laravel-wp-api/releases/tag/2.1.0

**Comment by kolefield** [comment]
Thanks, 2.1.0 works like a charm.

**Comment by kolefield** [comment]
BTW, @threesquared your fork of this repo doesn't have an issues page.

There's a problem with the changes you made to [this file](https://github.com/threesquared/laravel-wp-api/blob/ad9c74f2183c8a7189ada0e28f2eca179af3b781/src/Threesquared/LaravelWpApi/Facades/WpApi.php) which causes this error:

`FatalErrorException in WpApi.php line 6:
Cannot declare class Threesquared\LaravelWpApi\Facades\WpApi because the name is already in use`

**Comment by threesquared** [comment]
@kcaulkins Sorry about that, I have enabled issues now. Also I have fixed that issue in 2.1.1

**Comment by kolefield** [comment]
@threesquared Thanks, problem fixed! Appreciate your quick turnaround!
