### ISSUE TITLE
Laravel 5.2.* - php artisan vendor:publish - error

### ISSUE THREAD

**Issue by texeltexel2009** [Cyber-Duck/laravel-wp-api#7]
Hello Cyber-Duck,

I recently ran into an error while trying to install your package.
First off, I'd like to suggest to you to change the order of the steps for installing the package.
I think adding the ServiceProvider and Alias should go before trying to artisan vendor:publish.

The error comes when you try to "php artisan vendor:publish". Artisan echo's "Nothing to publish for tag []."
The Laravel Log shows:
"development.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::bindShared()' in J:\PhpstormProjects\peqnew\vendor\cyberduck\laravel-wp-api\src\Cyberduck\LaravelWpApi\LaravelWpApiServiceProvider.php:33".

Seems like the bindShared() method is deprecated and should be replaced with the bind() method adding an extra true or false parameter, as explained by Will Vincent on Laracasts forum:
https://laracasts.com/discuss/channels/laravel/laravel-52x-call-to-undefined-method-illuminatefoundationapplicationbindshared-error?page=1#reply-140221

In the end replacing this code in vendor\cyberduck\laravel-wp-api\src\Cyberduck\LaravelWpApi\LaravelWpApiServiceProvider.php:
`public function register() {
    $this->app->bindShared('wp-api', function ($app) {

```
    $endpoint = $this->app['config']->get('wp-api.endpoint');
        $auth     = $this->app['config']->get('wp-api.auth');
    $client   = $this->app->make('GuzzleHttp\Client');

    return new WpApi($endpoint, $client, $auth);
});

$this->app->bind('Cyberduck\LaravelWpApi\WpApi', function($app) {
    return $app['wp-api'];
    });
```

}`

with this fixed the problem and I successfully did a vendor:publish:
`public function register() {
    $this->app->bind('wp-api', function ($app) {

```
    $endpoint = $this->app['config']->get('wp-api.endpoint');
        $auth     = $this->app['config']->get('wp-api.auth');
    $client   = $this->app->make('GuzzleHttp\Client');

    return new WpApi($endpoint, $client, $auth);
}, true);

$this->app->bind('Cyberduck\LaravelWpApi\WpApi', function($app) {
    return $app['wp-api'];
    });
```

}`

Greetings

**Comment by threesquared** [comment]
Hi,

This repository is not maintained anymore. However I maintain a fork here https://github.com/threesquared/laravel-wp-api which has been updated to use the bind method.

Thanks

**Comment by texeltexel2009** [comment]
Yes, I saw the message on another closed issue just after posting this one. Closing this issue and moving on the the newer repo which works like a charm.

Thx and please keep up the nice contribution! ^^
